
name: iOS CI

on:
  push:
    branches: [ "main", "iOS-ELD-6-DEC" ]
  pull_request:
    branches: [ "main", "iOS-ELD-6-DEC" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show structure (debug)
        run: |
          find . -name "*.xcodeproj" -o -name "*.xcworkspace" | grep -v ".xcodeproj/project.xcworkspace"
          ls -la

      - name: Build and Test
        run: |
          if ls | grep -qi "\.xcworkspace$"; then
            FILE=$(ls | grep -i "\.xcworkspace$" | head -1)
            PARAM="workspace"
          else
            FILE=$(ls | grep -i "\.xcodeproj$" | head -1)
            PARAM="project"
          fi

          SCHEME=$(xcodebuild -"$PARAM" "$FILE" -list 2>/dev/null | awk '/Schemes:/,0' | tail -n +2 | head -1 | tr -d ' ')

          echo "FILE: $FILE"
          echo "PARAM: $PARAM"
          echo "SCHEME: $SCHEME"

          xcodebuild clean build \
            -"$PARAM" "$FILE" \
            -scheme "$SCHEME" \
           -destination 'platform=iOS Simulator,id=8D0474B3-1BD6-45B2-A9B9-219DBB956747' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=NO
