name: iOS CI

on:
  push:
    branches: [ "main", "iOS-ELD-6-DEC" ]
  pull_request:
    branches: [ "main", "iOS-ELD-6-DEC" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve Packages
        run: xcodebuild -resolvePackageDependencies -project NextEld.xcodeproj

      - name: Build App
        run: |
          xcodebuild clean build \
          -project NextEld.xcodeproj \
          -scheme NextEld \
          -destination 'generic/platform=iOS Simulator' \
          -derivedDataPath /tmp/DerivedData \
          CODE_SIGNING_ALLOWED=NO \
          COMPILER_INDEX_STORE_ENABLE=NO
